{% set version = '0.52.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-matrixstats
  version: {{ version|replace("-", "_") }}

source:
  fn: matrixStats_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/matrixStats_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/matrixStats/matrixStats_{{ version }}.tar.gz
  sha256: 39da6aa6b109f89a141dab8913d981abc4fbd3f8be9e206f92e382cc5270d2a5


  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: base64enc, ggplot2, knitr, microbenchmark, R.devices, R.rsp
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}make

  host:
    - {{r_impl}}

  run:
    - {{r_impl}}
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('matrixStats')"           # [not win]
    - "\"%R%\" -e \"library('matrixStats')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/HenrikBengtsson/matrixStats
  license: Artistic-2.0
  summary: High-performing functions operating on rows and columns of matrices, e.g. col / rowMedians(),
    col / rowRanks(), and col / rowSds().  Functions optimized per data type and for
    subsetted calculations such that both memory usage and processing time is minimized.  There
    are also optimized vector-based methods, e.g. binMeans(), madDiff() and weightedMedian().
  license_family: OTHER



# The original CRAN metadata for this package was:

# Package: matrixStats
# Version: 0.52.2
# Depends: R (>= 2.12.0)
# Suggests: base64enc, ggplot2, knitr, microbenchmark, R.devices, R.rsp
# VignetteBuilder: R.rsp
# Date: 2017-04-13
# Title: Functions that Apply to Rows and Columns of Matrices (and to Vectors)
# Authors@R: c( person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email="henrikb@braju.com"), person("Hector", "Corrada Bravo", role="ctb"), person("Robert", "Gentleman", role="ctb"), person("Ola", "Hossjer", role="ctb"), person("Harris", "Jaffee", role="ctb"), person("Dongcan", "Jiang", role="ctb"), person("Peter", "Langfelder", role="ctb"))
# Author: Henrik Bengtsson [aut, cre, cph], Hector Corrada Bravo [ctb], Robert Gentleman [ctb], Ola Hossjer [ctb], Harris Jaffee [ctb], Dongcan Jiang [ctb], Peter Langfelder [ctb]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Description: High-performing functions operating on rows and columns of matrices, e.g. col / rowMedians(), col / rowRanks(), and col / rowSds().  Functions optimized per data type and for subsetted calculations such that both memory usage and processing time is minimized.  There are also optimized vector-based methods, e.g. binMeans(), madDiff() and weightedMedian().
# License: Artistic-2.0
# LazyLoad: TRUE
# NeedsCompilation: yes
# ByteCompile: TRUE
# URL: https://github.com/HenrikBengtsson/matrixStats
# BugReports: https://github.com/HenrikBengtsson/matrixStats/issues
# RoxygenNote: 6.0.1
# Packaged: 2017-04-13 07:54:02 UTC; hb
# Repository: CRAN
# Date/Publication: 2017-04-14 14:49:54 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
