{% set version = '1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-loo
  version: {{ version|replace("-", "_") }}

source:
  fn: loo_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/loo_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/loo/loo_{{ version }}.tar.gz
  sha256: 3421202c546a9205d0f82f98525073df7546b6811a69bf1e127b8cbaf392015a


  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, rstan, rstanarm, testthat
requirements:
  build:
    - r-base
    - r-matrixstats >=0.50.0

  run:
    - r-base
    - r-matrixstats >=0.50.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('loo')"           # [not win]
    - "\"%R%\" -e \"library('loo')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://mc-stan.org/, https://groups.google.com/forum/#!forum/stan-users
  license: GPL (>= 3)
  summary: Efficient approximate leave-one-out cross-validation (LOO) using Pareto smoothed importance
    sampling (PSIS), a new procedure for regularizing importance weights. As a byproduct
    of the calculations, we also obtain approximate standard errors for estimated predictive
    errors and for the comparison of predictive errors between models. We also compute
    the widely applicable information criterion (WAIC).
  license_family: GPL3



# The original CRAN metadata for this package was:

# Package: loo
# Type: Package
# Title: Efficient Leave-One-Out Cross-Validation and WAIC for Bayesian Models
# Version: 1.1.0
# Date: 2016-03-27
# Authors@R: c(person("Aki", "Vehtari", email = "Aki.Vehtari@aalto.fi", role = c("aut")), person("Andrew", "Gelman", email = "gelman@stat.columbia.edu", role = c("aut")), person("Jonah", "Gabry", email = "jsg2201@columbia.edu", role = c("cre", "aut")), person("Juho", "Piironen", role = c("ctb")), person("Ben", "Goodrich", role = c("ctb")))
# Maintainer: Jonah Gabry <jsg2201@columbia.edu>
# URL: http://mc-stan.org/, https://groups.google.com/forum/#!forum/stan-users
# BugReports: https://github.com/stan-dev/loo/issues
# Description: Efficient approximate leave-one-out cross-validation (LOO) using Pareto smoothed importance sampling (PSIS), a new procedure for regularizing importance weights. As a byproduct of the calculations, we also obtain approximate standard errors for estimated predictive errors and for the comparison of predictive errors between models. We also compute the widely applicable information criterion (WAIC).
# License: GPL (>= 3)
# LazyData: TRUE
# Depends: R (>= 3.1.2)
# Imports: graphics, matrixStats (>= 0.50.0), parallel, stats
# Suggests: knitr, rmarkdown, rstan, rstanarm, testthat
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-03-27 14:54:10 UTC; jgabry
# Author: Aki Vehtari [aut], Andrew Gelman [aut], Jonah Gabry [cre, aut], Juho Piironen [ctb], Ben Goodrich [ctb]
# Repository: CRAN
# Date/Publication: 2017-03-27 15:21:52 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
