{% set version = '2.0.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-alr3
  version: {{ version|replace("-", "_") }}

source:
  fn: alr3_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/alr3_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/alr3/alr3_{{ version }}.tar.gz


  sha256: 809c1e9605142f047860a753314b0cf9e270c5b8cf4cb8869f6c6039c5d6397f
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-car

  run:
    - r-base
    - r-car

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('alr3')"  # [not win]
    - "\"%R%\" -e \"library('alr3')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http
  license: GPL (>= 2)
  summary: This package is a companion to the textbook S. Weisberg (2005),  "Applied Linear Regression,"
    3rd edition, Wiley. It includes all the data sets discussed in the book (except
    one), and a few functions that  are tailored to the methods discussed in the book.  As
    of version 2.0.0, this package depends on the car package. Many functions formerly  in
    alr3 have been renamed and now reside in car.   Data files have beeen lightly modified
    to make some data columns row labels.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: alr3
# Version: 2.0.5
# Date: 2011/10/27
# Title: Data to accompany Applied Linear Regression 3rd edition
# Author: Sanford Weisberg <sandy@umn.edu>
# Maintainer: Sanford Weisberg <sandy@umn.edu>
# Depends: R (>= 2.1.1), car
# LazyData: yes
# Description: This package is a companion to the textbook S. Weisberg (2005),  "Applied Linear Regression," 3rd edition, Wiley. It includes all the data sets discussed in the book (except one), and a few functions that  are tailored to the methods discussed in the book.  As of version 2.0.0, this package depends on the car package. Many functions formerly  in alr3 have been renamed and now reside in car.   Data files have beeen lightly modified to make some data columns row labels.
# License: GPL (>= 2)
# URL: http://www.r-project.org, http://www.stat.umn.edu/alr
# Packaged: 2011-10-27 18:09:45 UTC; sandy
# Repository: CRAN
# Date/Publication: 2011-10-27 19:35:19
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
