{% set version = '0.1-1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sparsesvd
  version: {{ version|replace("-", "_") }}

source:
  fn: sparsesvd_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sparsesvd_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sparsesvd/sparsesvd_{{ version }}.tar.gz


  sha256: c5fe3cea05167ac2b946dcd801f57c74c11629b6c36ec28c64fecebe919f1727
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-matrix
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-matrix
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sparsesvd')"  # [not win]
    - "\"%R%\" -e \"library('sparsesvd')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://tedlab.mit.edu/~dr/SVDLIBC/, http://wordspace.r-forge.r-project.org/
  license: BSD_3_clause + file LICENSE
  summary: Wrapper around the 'SVDLIBC' library for (truncated) singular value decomposition
    of a sparse matrix. Currently, only sparse real matrices in Matrix package format
    are supported.
  license_family: BSD

# The original CRAN metadata for this package was:

# Package: sparsesvd
# Title: Sparse Truncated Singular Value Decomposition (from 'SVDLIBC')
# Version: 0.1-1
# Date: 2016-04-23
# Authors@R: c(person("Doug", "Rohde", email="dr+svd@tedlab.mit.edu", role="aut"), person("Michael", "Berry", role="aut"), person("Theresa", "Do", role="aut"), person("Gavin", "O'Brien", role="aut"), person("Vijay", "Krishna", role="aut"), person("Sowmini", "Varadhan", role="aut"), person("University of Tennessee Research Foundation", role = "cph", comment = "files src/las2.c, src/svdlib.[ch], src/svdutil.[ch]"), person("Stefan", "Evert", email="stefan.evert@fau.de", role=c("cre", "aut", "cph"), comment="copyright holder for files src/main.c, R/*, man/*, tests/*"))
# Description: Wrapper around the 'SVDLIBC' library for (truncated) singular value decomposition of a sparse matrix. Currently, only sparse real matrices in Matrix package format are supported.
# Depends: R (>= 3.0)
# Imports: Matrix, methods
# License: BSD_3_clause + file LICENSE
# URL: http://tedlab.mit.edu/~dr/SVDLIBC/, http://wordspace.r-forge.r-project.org/
# NeedsCompilation: yes
# LazyData: true
# Packaged: 2016-04-23 18:51:13 UTC; evert
# Author: Doug Rohde [aut], Michael Berry [aut], Theresa Do [aut], Gavin O'Brien [aut], Vijay Krishna [aut], Sowmini Varadhan [aut], University of Tennessee Research Foundation [cph] (files src/las2.c, src/svdlib.[ch], src/svdutil.[ch]), Stefan Evert [cre, aut, cph] (copyright holder for files src/main.c, R/*, man/*, tests/*)
# Maintainer: Stefan Evert <stefan.evert@fau.de>
# Repository: CRAN
# Date/Publication: 2016-04-24 16:35:50

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
