{% set version = '2.2.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: pp
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/CDSoft/pp.git
  git_rev: {{ version }}

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  # rpaths:
  #   - lib/


requirements:
  build:
    - gmp
    - stack
    - posix                # [win]
    - {{native}}toolchain  # [win]

  run:
    - {{native}}gcc-libs   # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - pp -v

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://cdsoft.fr/pp/
  license: GPL-3
  summary: Pandoc preprocessor for literate programming
  license_family: GPL3
