{% set version = '0.2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-censusapi
  version: {{ version|replace("-", "_") }}

source:
  fn: censusapi_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/censusapi_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/censusapi/censusapi_{{ version }}.tar.gz


  sha256: 0be19adeb5fd54609d6767fc7b33fa7a5d74edaa170689b48ee8a4c42da7a1ab
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown
requirements:
  build:
    - r-base
    - r-httr
    - r-jsonlite

  run:
    - r-base
    - r-httr
    - r-jsonlite

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('censusapi')"  # [not win]
    - "\"%R%\" -e \"library('censusapi')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https
  license: MIT + file LICENSE
  summary: A wrapper for the U.S. Census Bureau APIs that returns data frames of  Census data
    and metadata. Available datasets include the  Decennial Census, American Community
    Survey, Small Area Health Insurance Estimates, Small Area Income and Poverty Estimates,
    and Population Estimates and Projections. See <https
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: censusapi
# Version: 0.2.1
# Title: Retrieve Data from the Census APIs
# Authors@R: person("Hannah", "Recht", email = "hrecht2@gmail.com", role = c("aut", "cre"))
# Description: A wrapper for the U.S. Census Bureau APIs that returns data frames of  Census data and metadata. Available datasets include the  Decennial Census, American Community Survey, Small Area Health Insurance Estimates, Small Area Income and Poverty Estimates, and Population Estimates and Projections. See <https://www.census.gov/data/developers/data-sets.html> for more information.
# URL: https://github.com/hrecht/censusapi
# BugReports: https://github.com/hrecht/censusapi/issues
# Depends: R (>= 3.0.0)
# License: MIT + file LICENSE
# LazyData: true
# RoxygenNote: 6.0.1
# Imports: httr, jsonlite
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2017-08-01 15:16:42 UTC; hrecht
# Author: Hannah Recht [aut, cre]
# Maintainer: Hannah Recht <hrecht2@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-08-01 15:37:36 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
