{% set version = '2.1-1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spam
  version: {{ version|replace("-", "_") }}

source:
  fn: spam_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/spam_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/spam/spam_{{ version }}.tar.gz


  sha256: acd3b00a4a3c8d61681620f11eb5d3b266ca911c0df09470bdcfeae1fcbddec8
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: spam64, fields, SparseM, Matrix, testthat, R.rsp, truncdist
requirements:
  build:
    - r-base
    - r-dotcall64
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-dotcall64
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('spam')"  # [not win]
    - "\"%R%\" -e \"library('spam')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.math.uzh.ch/furrer/software/spam/
  license: LGPL-2
  summary: 'Set of functions for sparse matrix algebra. Differences with other sparse matrix
    packages are: (1) we only support (essentially) one sparse matrix format, (2) based
    on transparent and simple structure(s), (3) tailored for MCMC calculations within
    G(M)RF. (4) and it is fast and scalable (with the extension package spam64).'

  license_family: LGPL

# The original CRAN metadata for this package was:

# Package: spam
# Type: Package
# Title: SPArse Matrix
# Version: 2.1-1
# Date: 2017-07-02
# Authors@R: c(person("Reinhard", "Furrer", role = c("aut", "cre"), email = "reinhard.furrer@math.uzh.ch"), person("Florian", "Gerber", role = "ctb", email = "florian.gerber@math.uzh.ch"), person("Daniel", "Gerber", role = "ctb", email = "daniel_gerber_2222@hotmail.com"), person("Kaspar", "Moesinger", role = "ctb", email = "kaspar.moesinger@gmail.com"), person("Youcef", "Saad", role = "ctb", comment = "SPARSEKIT http://www-users.cs.umn.edu/~saad/software/SPARSKIT/"), person(c("Esmond", "G."), "Ng", role = "ctb", comment = "Fortran Cholesky routines"), person(c("Barry", "W."), "Peyton", role = "ctb", comment = "Fortran Cholesky routines"), person(c("Joseph", "W.H."), "Liu", role = "ctb", comment = "Fortran Cholesky routines"), person(c("Alan", "D."), "George", role = "ctb", comment = "Fortran Cholesky routines") )
# Author: Reinhard Furrer [aut, cre], Florian Gerber [ctb], Daniel Gerber [ctb], Kaspar Moesinger [ctb], Youcef Saad [ctb] (SPARSEKIT http://www-users.cs.umn.edu/~saad/software/SPARSKIT/), Esmond G. Ng [ctb] (Fortran Cholesky routines), Barry W. Peyton [ctb] (Fortran Cholesky routines), Joseph W.H. Liu [ctb] (Fortran Cholesky routines), Alan D. George [ctb] (Fortran Cholesky routines)
# Maintainer: Reinhard Furrer <reinhard.furrer@math.uzh.ch>
# Depends: R (>= 3.1), dotCall64, grid, methods
# Suggests: spam64, fields, SparseM, Matrix, testthat, R.rsp, truncdist
# VignetteBuilder: R.rsp
# Description: Set of functions for sparse matrix algebra. Differences with other sparse matrix packages are: (1) we only support (essentially) one sparse matrix format, (2) based on transparent and simple structure(s), (3) tailored for MCMC calculations within G(M)RF. (4) and it is fast and scalable (with the extension package spam64).
# LazyLoad: Yes
# LazyData: Yes
# License: LGPL-2
# URL: http://www.math.uzh.ch/furrer/software/spam/
# NeedsCompilation: yes
# Packaged: 2017-07-02 19:23:04 UTC; furrer
# Repository: CRAN
# Date/Publication: 2017-07-03 09:53:05 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
